---
- name: Ensure cloudadmins group exists
  group:
    name: "{{ admin_group }}"
    state: present

- name: Create users and add to groups
  user:
    name: "{{ item }}"
    groups: "{{ admin_group }},wheel"
    append: yes
    generate_ssh_key: yes
    ssh_key_passphrase: ""
    state: present
  loop: "{{ users }}"

